### ISSUE TITLE
QueryEvents operation on AdminChannel

### ISSUE THREAD

**Issue by YvonneCeelie** [AxonIQ/axonserver-connector-java#154]
### Feature Description

There are usages where it is needed to query the events for a certain context.
It would be beneficial to add this operation to the new Admin API

Current implementation: 

```
// Performs a query on the event store, returns a stream of results.
  // Input is a stream to allow flow control from the client
  rpc QueryEvents (stream io.axoniq.axonserver.grpc.event.QueryEventsRequest) returns (stream io.axoniq.axonserver.grpc.event.QueryEventsResponse) {
  }
}
```

### Current Behaviour

Operation is not available.
### Wanted Behaviour

Operation is available.
### Possible Workarounds

N/A

**Comment by YvonneCeelie** [comment]
Going to try to use the eventChannel for this

**Comment by smcvb** [comment]
I'll close this issue as the Event Channel supports this behavior. Feel free to keep commenting under this if applicable.
