### ISSUE TITLE
Connector requires HANDLE_QUERIES and HANDLE_COMMANDS authorization when only dispatching queries or commands

### ISSUE THREAD

**Issue by abuijze** [AxonIQ/axonserver-connector-java#40]
When using the Query Channel in the connector, it pro-actively sets up the Query Stream with Axon Server, used to handle queries. When the authorizations are limited to only DISPATCH_QUERY, then the creation of the channel will generate many subsequent failures (and reattempts) to set up this Query Stream.

The same applies for the Command Channel.

The Query Channel and Command Channel should only set up their respective streams for inbound messages when at least one handler has been subscribed.

**Comment by smcvb** [comment]
Closing this issue as it has been resolved in pull request #41.
